# Generated by Django 5.0.1 on 2024-05-08 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("doc", models.FileField(upload_to="Book/")),
                ("title", models.CharField(max_length=100)),
                ("subtitle", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Gallerie",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("img", models.ImageField(blank=True, null=True, upload_to="Gallery/")),
                ("title", models.CharField(max_length=100)),
                ("subtitle", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("img1", models.ImageField(blank=True, null=True, upload_to="Images/")),
                ("img2", models.ImageField(blank=True, null=True, upload_to="Images/")),
                ("img3", models.ImageField(blank=True, null=True, upload_to="Images/")),
                ("title", models.CharField(max_length=100)),
                ("subtitle", models.CharField(max_length=100)),
                ("headline", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("link", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("subtitle", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ImageGallerie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imageprofile",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "idgallerie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.gallerie"
                    ),
                ),
            ],
        ),
    ]
