# Generated by Django 5.0.1 on 2024-05-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_imagegallerie_imageprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="description",
            field=models.CharField(max_length=5000),
        ),
    ]
