# Generated by Django 5.0.1 on 2024-05-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_news_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="Book/"),
        ),
    ]
