# Generated by Django 5.0.1 on 2024-05-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_book_created_at_book_updated_at_gallerie_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagegallerie",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="imagegallerie",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
