# Generated by Django 5.0.1 on 2024-05-24 10:50

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_imagegallerie_created_at_imagegallerie_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"verbose_name_plural": "News"},
        ),
        migrations.AlterField(
            model_name="imagegallerie",
            name="idgallerie",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.gallerie",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdf12345",
                length=10,
                max_length=20,
                prefix="news",
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
