# Generated by Django 5.0.1 on 2024-05-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_alter_news_options_alter_imagegallerie_idgallerie_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallerie",
            options={"verbose_name_plural": "Galleries"},
        ),
        migrations.AlterField(
            model_name="gallerie",
            name="description",
            field=models.CharField(max_length=5000),
        ),
    ]
