# Generated by Django 5.0.1 on 2024-05-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_gallerie_options_alter_gallerie_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallerie",
            name="description",
            field=models.TextField(max_length=5000),
        ),
    ]
