# Generated by Django 5.0.1 on 2024-05-24 11:11

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_alter_gallerie_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagegallerie",
            options={"verbose_name_plural": "ImageGallerie"},
        ),
        migrations.AlterField(
            model_name="gallerie",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdf12345",
                length=10,
                max_length=20,
                prefix="gal",
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="imagegallerie",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdf12345",
                length=10,
                max_length=20,
                prefix="img",
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
