# Generated by Django 5.0.1 on 2024-05-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_alter_imagegallerie_options_alter_gallerie_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagegallerie",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
