# Generated by Django 5.0.1 on 2024-05-24 11:28

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_alter_imagegallerie_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdf12345",
                length=10,
                max_length=20,
                prefix="book",
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdf12345",
                length=10,
                max_length=20,
                prefix="vid",
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
