# Generated by Django 5.0.1 on 2024-05-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_alter_book_id_alter_video_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="description",
        ),
        migrations.RemoveField(
            model_name="news",
            name="headline",
        ),
        migrations.AddField(
            model_name="news",
            name="description1",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="description2",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="description3",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="headline1",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="headline2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="headline3",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
