# Generated by Django 5.0.1 on 2024-05-30 06:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_news_description3"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="img1",
            new_name="img",
        ),
        migrations.RemoveField(
            model_name="news",
            name="description1",
        ),
        migrations.RemoveField(
            model_name="news",
            name="description2",
        ),
        migrations.RemoveField(
            model_name="news",
            name="description3",
        ),
        migrations.RemoveField(
            model_name="news",
            name="headline2",
        ),
        migrations.RemoveField(
            model_name="news",
            name="headline3",
        ),
        migrations.RemoveField(
            model_name="news",
            name="img2",
        ),
        migrations.RemoveField(
            model_name="news",
            name="img3",
        ),
        migrations.RemoveField(
            model_name="news",
            name="subtitle",
        ),
        migrations.AddField(
            model_name="news",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, default="description", null=True
            ),
        ),
    ]
