# Generated by Django 5.0.1 on 2024-05-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_rename_img1_news_img_remove_news_description1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="img",
            new_name="img1",
        ),
        migrations.AddField(
            model_name="news",
            name="img2",
            field=models.ImageField(blank=True, null=True, upload_to="Images/"),
        ),
        migrations.AddField(
            model_name="news",
            name="img3",
            field=models.ImageField(blank=True, null=True, upload_to="Images/"),
        ),
    ]
