# Generated by Django 5.0.1 on 2024-05-31 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0018_rename_img_news_img1_news_img2_news_img3"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="Gallery/"),
        ),
    ]
