# Generated by Django 5.0.1 on 2024-05-31 05:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_video_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="subtitle",
        ),
        migrations.AddField(
            model_name="video",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, default="description", null=True
            ),
        ),
    ]
