# Generated by Django 5.0.1 on 2024-05-31 10:55

import ckeditor_uploader.fields
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_remove_video_subtitle_video_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfoGal",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdf12345",
                        length=10,
                        max_length=20,
                        prefix="info",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("img", models.ImageField(blank=True, null=True, upload_to="Infopro/")),
                ("title", models.CharField(max_length=100)),
                (
                    "description",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, default="description", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "InfoGalleries",
            },
        ),
        migrations.CreateModel(
            name="Infoprof",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdf12345",
                        length=10,
                        max_length=20,
                        prefix="prof",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("tel", models.CharField(max_length=50)),
                (
                    "description",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, default="description", null=True
                    ),
                ),
            ],
        ),
    ]
