# Generated by Django 5.0.1 on 2024-05-31 12:55

import ckeditor_uploader.fields
import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0021_infogal_infoprof"),
    ]

    operations = [
        migrations.CreateModel(
            name="Infocourse",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdf12345",
                        length=10,
                        max_length=20,
                        prefix="cou",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "description",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, default="description", null=True
                    ),
                ),
                (
                    "professeur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.infoprof",
                    ),
                ),
            ],
        ),
    ]
