# Generated by Django 5.0.1 on 2024-06-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0022_infocourse"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="categorie",
            field=models.CharField(
                blank=True,
                choices=[("dine", "Dine"), ("generale", "Generale")],
                default="Dine",
                max_length=50,
            ),
        ),
    ]
