# Generated by Django 5.0.1 on 2024-06-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0023_video_categorie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="categorie",
            field=models.CharField(
                blank=True,
                choices=[("dine", "Dine"), ("generale", "Generale")],
                default="Generale",
                max_length=50,
            ),
        ),
    ]
