# Generated by Django 5.0.1 on 2024-06-03 13:31

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0025_playlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="subtitle",
        ),
        migrations.AddField(
            model_name="book",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, default="description", null=True
            ),
        ),
    ]
