# Generated by Django 5.0.1 on 2024-06-04 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0026_remove_book_subtitle_book_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlist",
            name="video",
        ),
        migrations.AddField(
            model_name="video",
            name="video",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="playlist",
                to="main.playlist",
            ),
        ),
    ]
