# Generated by Django 5.0.1 on 2024-06-04 12:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0027_remove_playlist_video_video_video"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="video",
            new_name="playlist",
        ),
    ]
