# Generated by Django 5.0.1 on 2024-06-04 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0029_alter_video_playlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="playlist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="video",
                to="main.playlist",
            ),
        ),
    ]
